spring:
  datasource:
    url: jdbc:mysql://localhost/spring_security
    username: honey
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always